spring:
  application:
    name: backend
  liquibase:
    change-log: classpath:db/changelog/app-changelog.xml
    enabled: true
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/malickov
    username: root


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

security:
  bcrypt:
    strength: 12
  JwtValidityMillis: 18000000