spring:
  liquibase:
    contexts: prod


security:
  JwtValidityMillis: 90000000
  corsSite: https://nejlepsi-skolky.cz , https://www.nejlepsi-skolky.cz

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false