spring:
  application:
    name: backend
  liquibase:
    enabled: true
  profiles:
    active: prod
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

security:
  bcrypt:
    strength: 12

logging:
  level:
    root: INFO
  file:
    name: logs/app.log
    path: ./logs
  logback:
    rollingpolicy:
      max-history: 14
      total-size-cap: 1GB