spring:
  application:
    name: backend
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/app-changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/malickov
    username: BEuser
    password: mypassword
security:
  JwtValidityMillis: 28800000
  secretKey: vkAnPL4ZXtMP3D/Hxu6Em3PygtJzKWOSf2BngH3Ynm0=


server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore-dev.p12
    key-store-password: veryStrongAndHiddenPassword
    key-alias: local-ssl

springdoc: # swagger
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true