spring:
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/app-changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/malickov
    username: BEuser
    password: mypassword

security:
  JwtValidityMillis: 28800000
  secretKey: vkAnPL4ZXtMP3D/Hxu6Em3PygtJzKWOSf2BngH3Ynm0=

server:
  port: 0
  ssl:
    enabled: false # no fucking SSL for tests