spring:
  liquibase:
    contexts: prod
    change-log: classpath:db/changelog/app-changelog.xml

security:
  JwtValidityMillis: 900000
  corsSite: https://nejlepsi-skolky.cz , https://www.nejlepsi-skolky.cz

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false