spring:
  application:
    name: backend
  liquibase:
    enabled: true
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/malickov
    username: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

security:
  bcrypt:
    strength: 12

logging:
  level:
    root: INFO
  file:
    name: app.log
    path: ./logs