--liquibase formatted sql

--changeset Martin_Fischer:1 context:dev,prod

CREATE TABLE "user" (
                        user_uuid uuid DEFAULT uuidv7() PRIMARY KEY,
                        first_name VARCHAR(100) NOT NULL,
                        last_name VARCHAR(100) NOT NULL,
                        email VARCHAR(100) NOT NULL,
                        password VARCHAR(255),
                        active BOOLEAN DEFAULT TRUE,
                        role_name VARCHAR(55),
                        credit NUMERIC(11,2) DEFAULT 0,
                        UNIQUE(email)
);

--changeset Martin_Fischer:2 context:dev
INSERT INTO "user" (first_name, last_name, email, active, role_name, password)
VALUES
    ('Martin', 'Fischer', '1@1.cz', TRUE, 'DIRECTOR', '$2a$12$KeVi5xNQGqtFqALo355CMudCpNEiwDbv5O/75ML7wnqu4cdcpHzf.'),
    ('Sarka', 'Fischer','2@2.cz', TRUE, 'MANAGER', '$2a$12$KeVi5xNQGqtFqALo355CMudCpNEiwDbv5O/75ML7wnqu4cdcpHzf.'),
    ('Charlie', 'Brown','3@3.cz', TRUE, 'TEACHER', '$2a$12$KeVi5xNQGqtFqALo355CMudCpNEiwDbv5O/75ML7wnqu4cdcpHzf.'),
    ('Sam', 'Quited','4@4.cz', FALSE, 'PARENT', '$2a$12$KeVi5xNQGqtFqALo355CMudCpNEiwDbv5O/75ML7wnqu4cdcpHzf.'),
    ('Tom', 'Skala','5@5.cz', TRUE, 'PARENT', '$2a$12$KeVi5xNQGqtFqALo355CMudCpNEiwDbv5O/75ML7wnqu4cdcpHzf.'),
    ('Jack', 'Montana','6@6.cz', TRUE, 'PARENT', '$2a$12$KeVi5xNQGqtFqALo355CMudCpNEiwDbv5O/75ML7wnqu4cdcpHzf.');

--changeset Martin_Fischer:3 context:dev,prod

CREATE TABLE identificator (
                               identificator_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               identificator VARCHAR(50) NOT NULL
);

CREATE TABLE child (
                       child_uuid uuid DEFAULT uuidv7() PRIMARY KEY,
                       first_name VARCHAR(100) NOT NULL,
                       last_name VARCHAR(100) NOT NULL,
                       department VARCHAR(55) NOT NULL,
                       birthday TIMESTAMP(6) NOT NULL,
                       active BOOLEAN DEFAULT TRUE,
                       notes VARCHAR(255),
                       user_uuid uuid NOT NULL,
                       identificator_id INT,
                       mon BOOLEAN DEFAULT FALSE,
                       tue BOOLEAN DEFAULT FALSE,
                       wed BOOLEAN DEFAULT FALSE,
                       thu BOOLEAN DEFAULT FALSE,
                       fri BOOLEAN DEFAULT FALSE,
                       FOREIGN KEY (user_uuid) REFERENCES "user"(user_uuid) ON DELETE CASCADE,
                       FOREIGN KEY (identificator_id) REFERENCES identificator(identificator_id)
);

CREATE TABLE attendance (
                            attendance_uuid uuid DEFAULT uuidv7() PRIMARY KEY,
                            child_uuid uuid NOT NULL,
                            date TIMESTAMP(6) NOT NULL,
                            plan_arrival TIME NOT NULL,
                            plan_leaving TIME NOT NULL,
                            arrival TIME,
                            leaving TIME,
                            excuse VARCHAR(255),
                            late_excuse VARCHAR(255),
                            modified_by INT NOT NULL,
                            modified_at TIMESTAMP,
                            department VARCHAR(55) NOT NULL,
                            FOREIGN KEY (child_uuid) REFERENCES child(child_uuid) ON DELETE CASCADE
);

--changeset Martin_Fischer:4 context:dev
INSERT INTO identificator (identificator)
VALUES ('Sovička'), ('Srdíčko'), ('Kačenka do vody'), ('Houba');

INSERT INTO child (first_name, last_name, department, birthday, identificator_id, user_uuid)
VALUES
    ('Laura', 'Skala', 'KINDERGARTEN', '2020-01-17', 1,
     (SELECT user_uuid FROM "user" WHERE email='5@5.cz')),
    ('Mia', 'Skala', 'NURSERY2', '2022-02-01', 4,
     (SELECT user_uuid FROM "user" WHERE email='5@5.cz')),
    ('Lucie', 'Montana', 'NURSERY1', '2021-05-17', 2,
     (SELECT user_uuid FROM "user" WHERE email='6@6.cz')),
    ('Tereza', 'Montana', 'NURSERY2', '2022-07-01', 3,
     (SELECT user_uuid FROM "user" WHERE email='6@6.cz'));
