--liquibase formatted sql

--changeset Martin_Fischer:1 context:dev,prod

CREATE TABLE "user" (
                        user_uuid uuid DEFAULT uuidv7() PRIMARY KEY,
                        first_name VARCHAR(100) NOT NULL,
                        last_name VARCHAR(100) NOT NULL,
                        email VARCHAR(100) NOT NULL,
                        telephone VARCHAR(100),
                        password VARCHAR(255),
                        active BOOLEAN DEFAULT TRUE,
                        identifier VARCHAR(100) NOT NULL,  -- used for bank transfers
                        role_name VARCHAR(55),
                        credit NUMERIC(11,2) DEFAULT 0,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        UNIQUE(email)
);

CREATE TABLE identificator (
                               identificator_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               identificator_name VARCHAR(50) NOT NULL
);

CREATE TABLE child (
                       child_uuid uuid DEFAULT uuidv7() PRIMARY KEY,
                       first_name VARCHAR(100) NOT NULL,
                       last_name VARCHAR(100) NOT NULL,
                       department VARCHAR(55) NOT NULL,
                       birthday TIMESTAMP(6) NOT NULL,
                       active BOOLEAN DEFAULT TRUE,
                       notes VARCHAR(255),
                       user_uuid uuid NOT NULL,
                       identificator_id INT,
                       mon BOOLEAN DEFAULT FALSE,
                       tue BOOLEAN DEFAULT FALSE,
                       wed BOOLEAN DEFAULT FALSE,
                       thu BOOLEAN DEFAULT FALSE,
                       fri BOOLEAN DEFAULT FALSE,
                       FOREIGN KEY (user_uuid) REFERENCES "user"(user_uuid) ON DELETE CASCADE,
                       FOREIGN KEY (identificator_id) REFERENCES identificator(identificator_id),
                       CONSTRAINT fk_child_identificator FOREIGN KEY (identificator_id)
                               REFERENCES identificator(identificator_id)
                               ON DELETE SET NULL
);

CREATE TABLE attendance (
                            attendance_uuid uuid DEFAULT uuidv7() PRIMARY KEY,
                            child_uuid uuid NOT NULL,
                            attendance_date DATE NOT NULL,
                            plan_arrival TIME NOT NULL,
                            plan_leaving TIME NOT NULL,
                            arrival TIME,
                            leaving TIME,
                            excuse VARCHAR(255),
                            late_excuse VARCHAR(255),
                            modified_by uuid NOT NULL,
                            modified_at TIMESTAMP,
                            department VARCHAR(55) NOT NULL,
                            FOREIGN KEY (child_uuid) REFERENCES child(child_uuid) ON DELETE CASCADE,
                            CONSTRAINT uq_attendance_child_date UNIQUE (child_uuid, attendance_date)
);

--  holidays and ad-hoc closure days
CREATE TABLE holiday (
                              holiday_date DATE PRIMARY KEY
);



--changeset Martin_Fischer:2 context:dev,prod
INSERT INTO identificator (identificator_name) VALUES
                                                   ('Slon'),
                                                   ('Lev'),
                                                   ('Osel'),
                                                   ('Prasátko'),
                                                   ('Kačer'),
                                                   ('Žirafa'),
                                                   ('Klokan'),
                                                   ('Želva'),
                                                   ('Kuře'),
                                                   ('Kravička'),
                                                   ('Opice'),
                                                   ('Tygr'),
                                                   ('Ovečka'),
                                                   ('Veverka'),
                                                   ('Liška'),
                                                   ('Hroch'),
                                                   ('Zebra'),
                                                   ('Kočka'),
                                                   ('Zajíc'),
                                                   ('Modrý koník'),
                                                   ('Dráček'),
                                                   ('Srnka'),
                                                   ('Myška'),
                                                   ('Pejsek'),
                                                   ('Medvěd'),
                                                   ('Plážový míč'),
                                                   ('Kačenka do vody'),
                                                   ('Kyblík'),
                                                   ('Štětce'),
                                                   ('Pastelky'),
                                                   ('Kostka'),
                                                   ('Skateboard'),
                                                   ('Buben'),
                                                   ('Plyšový Medvěd'),
                                                   ('Lopatky'),
                                                   ('Kočárek'),
                                                   ('Houpací kůň'),
                                                   ('Knížka'),
                                                   ('Káča'),
                                                   ('Autíčko'),
                                                   ('Balónek'),
                                                   ('Koloběžka'),
                                                   ('Panenka'),
                                                   ('Vláček'),
                                                   ('Fotbalový míč'),
                                                   ('Švihadlo'),
                                                   ('Stavebnice'),
                                                   ('Korálky'),
                                                   ('Papírový drak'),
                                                   ('Šašek'),
                                                   ('Kytka'),
                                                   ('Sluníčko'),
                                                   ('Pórek'),
                                                   ('Ředkev'),
                                                   ('Třešeň'),
                                                   ('Čmelák'),
                                                   ('Motýl'),
                                                   ('Paprika'),
                                                   ('Banán'),
                                                   ('Citrón'),
                                                   ('Ježek'),
                                                   ('Houba'),
                                                   ('Okurka'),
                                                   ('Jablko'),
                                                   ('Jahoda'),
                                                   ('Žabka'),
                                                   ('Hrášek'),
                                                   ('Cibule'),
                                                   ('Švestka'),
                                                   ('Hrozno'),
                                                   ('Mrkev'),
                                                   ('Zelí'),
                                                   ('Hruška'),
                                                   ('Rajče'),
                                                   ('Ptáček');
INSERT INTO holiday (holiday_date) VALUES
-- 2026
('2026-09-28'),
('2026-10-28'),
('2026-11-17'),
('2026-12-24'),
('2026-12-25'),
('2026-12-26'),

-- 2027
('2027-01-01'),
('2027-03-26'), -- Good Friday
('2027-03-29'), -- Easter Monday
('2027-05-01'),
('2027-05-08'),
('2027-07-05'),
('2027-07-06'),
('2027-09-28'),
('2027-10-28'),
('2027-11-17'),
('2027-12-24'),
('2027-12-25'),
('2027-12-26'),

-- 2028
('2028-01-01'),
('2028-04-14'), -- Good Friday
('2028-04-17'), -- Easter Monday
('2028-05-01'),
('2028-05-08'),
('2028-07-05'),
('2028-07-06'),
('2028-09-28'),
('2028-10-28'),
('2028-11-17'),
('2028-12-24'),
('2028-12-25'),
('2028-12-26'),

-- 2029
('2029-01-01'),
('2029-03-30'), -- Good Friday
('2029-04-02'), -- Easter Monday
('2029-05-01'),
('2029-05-08'),
('2029-07-05'),
('2029-07-06'),
('2029-09-28'),
('2029-10-28'),
('2029-11-17'),
('2029-12-24'),
('2029-12-25'),
('2029-12-26');


INSERT INTO "user" (first_name, last_name, email,telephone, active, role_name, password,identifier)
VALUES
    ('Šárka', 'Fischer', 'info@malickov.cz', '+420 777 574 823',TRUE, 'DIRECTOR', Null, '1111');


--changeset Martin_Fischer:3 context:dev,prod
INSERT INTO "user" (first_name, last_name, email,telephone, active, role_name, password,identifier)
VALUES
    ('Martin', 'Fischer', 'director@cz.cz','123 456 347' ,TRUE, 'DIRECTOR', '$2a$12$KeVi5xNQGqtFqALo355CMudCpNEiwDbv5O/75ML7wnqu4cdcpHzf.', '1111'),
    ('Sarka', 'Fischer','manager@cz.cz','+420 777 282 591', TRUE, 'MANAGER', '$2a$12$KeVi5xNQGqtFqALo355CMudCpNEiwDbv5O/75ML7wnqu4cdcpHzf.', '2222'),
    ('Charlie', 'Brown','teacher@cz.cz', '123456789',TRUE, 'TEACHER', '$2a$12$KeVi5xNQGqtFqALo355CMudCpNEiwDbv5O/75ML7wnqu4cdcpHzf.','3333'),
    ('Sam', 'Quited','parentQuit@4.cz', '123456789',FALSE, 'PARENT', '$2a$12$KeVi5xNQGqtFqALo355CMudCpNEiwDbv5O/75ML7wnqu4cdcpHzf.','4444'),
    ('Tom', 'Skala','parent2@cz.cz', '123456789',TRUE, 'PARENT', '$2a$12$KeVi5xNQGqtFqALo355CMudCpNEiwDbv5O/75ML7wnqu4cdcpHzf.','5555'),
    ('Jack', 'Montana','parent@cz.cz', '123456789',TRUE, 'PARENT', '$2a$12$KeVi5xNQGqtFqALo355CMudCpNEiwDbv5O/75ML7wnqu4cdcpHzf.','6666');

INSERT INTO child (first_name, last_name, department, birthday, identificator_id, user_uuid)
VALUES
    ('Laura', 'Skala', 'KINDERGARTEN', '2020-01-17', 1,
     (SELECT user_uuid FROM "user" WHERE email='parent2@cz.cz')),
    ('Mia', 'Skala', 'NURSERY2', '2022-02-01', 4,
     (SELECT user_uuid FROM "user" WHERE email='parent2@cz.cz')),
    ('Lucie', 'Montana', 'NURSERY1', '2021-05-17', 2,
     (SELECT user_uuid FROM "user" WHERE email='parent@cz.cz')),
    ('Tereza', 'Montana', 'NURSERY2', '2022-07-01', 3,
     (SELECT user_uuid FROM "user" WHERE email='parent@cz.cz'));





