package cz.malickov.backend.mapper;

import cz.malickov.backend.dto.ChildInboundDTO;
import cz.malickov.backend.dto.ChildOutboundDTO;
import cz.malickov.backend.entity.Child;
import org.mapstruct.*;

@Mapper(componentModel = "spring")
public interface ChildMapper {

    /**
     * Create a new Child entity based on inbound DTO.
     * - childUuid is generated by JPA, so we ignore it here.
     */
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "childUuid", ignore = true)
    Child toEntity(ChildInboundDTO dto);

    /**
     * Update an existing Child entity  based on inbound DTO.
     *   IGNORE is used for nulls to be safe;
     *   if later some DTO fields are made nullable, they won't overwrite non-null entity fields with null.
     */
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "childUuid", ignore = true)
    void updateEntity(ChildInboundDTO dto, @MappingTarget Child child); // only 5 fields can be updated

    /**
     * Create a new outbound Record from Child entity
     */
    ChildOutboundDTO toOutboundDTO(Child child);

}