package cz.malickov.backend.mapper;

import cz.malickov.backend.dto.UserInboundDTO;
import cz.malickov.backend.dto.UserOutboundDTO;
import cz.malickov.backend.entity.User;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(componentModel = "spring")
public interface UserMapper {

    /**
     * Create a new User entity from inbound DTO.
     * - userUuid is generated by JPA, so we ignore it here.
     * - password, credit, and children are not supplied by the inbound DTO and are ignored.
     * - DTO.role -> entity.roleName
     */
    @Mapping(target = "userUuid", ignore = true)
    @Mapping(target = "password", ignore = true)
    @Mapping(target = "credit", ignore = true)
    @Mapping(target = "children", ignore = true)
    @Mapping(source = "role", target = "roleName")
    User toEntity(UserInboundDTO dto);

    /**
     * Update an existing User entity in-place from inbound DTO.
     * - Keeps existing userUuid, password, credit, and children intact.
     * - DTO.role -> entity.roleName
     * - Because the DTO fields are all required (except id), we use IGNORE for nulls to be safe;
     *   if you later make some DTO fields nullable, they won't overwrite non-null entity fields with null.
     */
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "userUuid", ignore = true)
    @Mapping(target = "password", ignore = true)
    @Mapping(target = "credit", ignore = true)
    @Mapping(target = "children", ignore = true)
    @Mapping(source = "role", target = "roleName")
    void updateEntity(UserInboundDTO dto, @MappingTarget User user);



    @Mapping(source = "roleName", target = "role")
    UserOutboundDTO toOutboundDTO(User user);

}