package cz.malickov.backend.mapper;

import cz.malickov.backend.dto.UserInboundDTO;
import cz.malickov.backend.dto.UserOutboundDTO;
import cz.malickov.backend.entity.User;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(componentModel = "spring")
public interface UserMapper {

    /**
     * Create a new User entity from inbound DTO.
     * - userUuid is generated by JPA, so we ignore it here.
     * - password, credit, and children are not supplied by the inbound DTO and are ignored.
     * - DTO.role -> entity.roleName
     */
    @Mapping(target = "userUuid", ignore = true)
    @Mapping(target = "password", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(source = "role", target = "roleName")
    @Mapping(target = "credit", ignore = true)
    User toEntity(UserInboundDTO dto);

    /**
     * Update an existing User entity  from inbound DTO.
     * - Keeps existing userUuid, password, credit, and identifier intact.
     * - DTO.role -> entity.roleName
     *   IGNORE is used for nulls to be safe;
     *   if later some DTO fields are made nullable, they won't overwrite non-null entity fields with null.
     */
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "userUuid", ignore = true)
    @Mapping(target = "password", ignore = true)
    @Mapping(target = "credit", ignore = true)
    @Mapping(target = "identifier", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "children", ignore = true)
    @Mapping(source = "role", target = "roleName")
    void updateEntity(UserInboundDTO dto, @MappingTarget User user); // only 4 fields can be updated



    @Mapping(source = "roleName", target = "role")
    @Mapping(target = "credit", source="credit", defaultValue = "0")
    UserOutboundDTO toOutboundDTO(User user);

}